apiVersion: ray.io/v1
kind: RayCluster
metadata:
  name: jobtest
spec:
  headGroupSpec:
    rayStartParams:
      block: "true"
      dashboard-host: 127.0.0.1
      num-gpus: "0"
    serviceType: ClusterIP
    template:
      spec:
        containers:
        - env:
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          image: quay.io/project-codeflare/ray:latest-py39-cu118
          imagePullPolicy: Always
          lifecycle:
            preStop:
              exec:
                command:
                - /bin/sh
                - -c
                - ray stop
          name: ray-head
          ports:
          - containerPort: 6379
            name: gcs
            protocol: TCP
          - containerPort: 8265
            name: dashboard
            protocol: TCP
          - containerPort: 10001
            name: client
            protocol: TCP
          resources:
            limits:
              cpu: 2
              memory: 4G
              nvidia.com/gpu: 0
            requests:
              cpu: 2
              memory: 4G
              nvidia.com/gpu: 0
          volumeMounts:
          - mountPath: /etc/tls/private
            name: proxy-tls-secret
            readOnly: true
        - args:
          - --https-address=:8443
          - --provider=openshift
          - --openshift-service-account=jobtest-oauth-proxy
          - --upstream=http://localhost:8265
          - --tls-cert=/etc/tls/private/tls.crt
          - --tls-key=/etc/tls/private/tls.key
          - --cookie-secret=SECRET
          - --openshift-delegate-urls={"/":{"resource":"pods","namespace":"default","verb":"get"}}
          image: registry.redhat.io/openshift4/ose-oauth-proxy@sha256:1ea6a01bf3e63cdcf125c6064cbd4a4a270deaf0f157b3eabb78f60556840366
          name: oauth-proxy
          ports:
          - containerPort: 8443
            name: oauth-proxy
            protocol: TCP
          resources: {}
          volumeMounts:
          - mountPath: /etc/tls/private
            name: proxy-tls-secret
            readOnly: true
        imagePullSecrets: []
        serviceAccount: jobtest-oauth-proxy
        volumes:
        - name: proxy-tls-secret
          secret:
            secretName: jobtest-proxy-tls-secret
  rayVersion: 2.7.0
  workerGroupSpecs:
  - groupName: small-group-jobtest
    maxReplicas: 2
    minReplicas: 2
    rayStartParams:
      block: "true"
      num-gpus: "0"
    replicas: 2
    template:
      metadata:
        annotations:
          key: value
        labels:
          key: value
      spec:
        containers:
        - env:
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          image: quay.io/project-codeflare/ray:latest-py39-cu118
          lifecycle:
            preStop:
              exec:
                command:
                - /bin/sh
                - -c
                - ray stop
          name: machine-learning
          resources:
            limits:
              cpu: 1
              memory: 4G
              nvidia.com/gpu: 0
            requests:
              cpu: 1
              memory: 4G
              nvidia.com/gpu: 0
        imagePullSecrets: []
        initContainers:
        - command:
          - sh
          - -c
          - until nslookup $RAY_IP.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local;
            do echo waiting for myservice; sleep 2; done
          image: quay.io/project-codeflare/busybox:1.28
          name: init-myservice
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: jobtest-proxy-tls-secret
  name: jobtest-oauth
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: oauth-proxy
    port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    app.kubernetes.io/created-by: kuberay-operator
    app.kubernetes.io/name: kuberay
    ray.io/cluster: jobtest
    ray.io/identifier: jobtest-head
    ray.io/node-type: head
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.primary: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"jobtest-oauth-proxy"}}'
  name: jobtest-oauth-proxy
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: jobtest-oauth-proxy
spec:
  to:
    kind: Service
    name: jobtest-oauth
  tls:
    termination: Reencrypt
